# FILEPATH: /home/marcelo/dev/mongodb/mongo01/routes.http
# BASE_URL: http://localhost:3000

# Criar um novo vídeo
POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Meu vídeo 2",
    "description": "Descrição do meu vídeo 2",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}

### Listar todos os vídeos

GET http://localhost:3000/videos

### Listar um vídeo específico 

GET http://localhost:3000/videos/fe87d5a9-86c3-4f47-abd2-1a27d24d6d2f

### Atualizar um vídeo 

PUT http://localhost:3000/videos/fe87d5a9-86c3-4f47-abd2-1a27d24d6d2f
Content-Type: application/json

{
    "title": "Meu vídeo 2 atualizado",
    "description": "Descrição do meu vídeo 2 atualizado",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}

### Deletar um vídeo

DELETE http://localhost:3000/videos/fe87d5a9-86c3-4f47-abd2-1a27d24d6d2f

### Inativar um vídeo

PUT http://localhost:3000/videos/1370eb08-b487-4287-8fd0-488598b81fbf/inactivate

### Ativar um vídeo

PUT http://localhost:3000/videos/1370eb08-b487-4287-8fd0-488598b81fbf/activate